name: Docker Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t mcp-typescript-simple .

      - name: Test Docker image (smoke test)
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          # Basic smoke test - container should start and exit gracefully
          timeout 10s docker run --rm \
            -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
            -e OPENAI_API_KEY="$OPENAI_API_KEY" \
            -e GOOGLE_API_KEY="$GOOGLE_API_KEY" \
            mcp-typescript-simple || [ $? -eq 124 ]
